# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from avl_bsd_translator/PassthroughMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PassthroughMsg(genpy.Message):
  _md5sum = "68cb8a05d5ebb8373e58b01f1c0af317"
  _type = "avl_bsd_translator/PassthroughMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#===============================================================================
# Autonomous Vehicle Library Backseat Driver
#
# Description: Defines a message that contains a passthrough message
#===============================================================================

uint8 ORIGIN_ID
uint8 TARGET_ID
uint8 CHANNEL
uint8 INTERFACE
string DATA
"""
  __slots__ = ['ORIGIN_ID','TARGET_ID','CHANNEL','INTERFACE','DATA']
  _slot_types = ['uint8','uint8','uint8','uint8','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ORIGIN_ID,TARGET_ID,CHANNEL,INTERFACE,DATA

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PassthroughMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ORIGIN_ID is None:
        self.ORIGIN_ID = 0
      if self.TARGET_ID is None:
        self.TARGET_ID = 0
      if self.CHANNEL is None:
        self.CHANNEL = 0
      if self.INTERFACE is None:
        self.INTERFACE = 0
      if self.DATA is None:
        self.DATA = ''
    else:
      self.ORIGIN_ID = 0
      self.TARGET_ID = 0
      self.CHANNEL = 0
      self.INTERFACE = 0
      self.DATA = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.ORIGIN_ID, _x.TARGET_ID, _x.CHANNEL, _x.INTERFACE))
      _x = self.DATA
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.ORIGIN_ID, _x.TARGET_ID, _x.CHANNEL, _x.INTERFACE,) = _get_struct_4B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.DATA = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.DATA = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.ORIGIN_ID, _x.TARGET_ID, _x.CHANNEL, _x.INTERFACE))
      _x = self.DATA
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.ORIGIN_ID, _x.TARGET_ID, _x.CHANNEL, _x.INTERFACE,) = _get_struct_4B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.DATA = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.DATA = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
