// Generated by gencpp from file avl_bsd_translator/ActionMsg.msg
// DO NOT EDIT!


#ifndef AVL_BSD_TRANSLATOR_MESSAGE_ACTIONMSG_H
#define AVL_BSD_TRANSLATOR_MESSAGE_ACTIONMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avl_bsd_translator
{
template <class ContainerAllocator>
struct ActionMsg_
{
  typedef ActionMsg_<ContainerAllocator> Type;

  ActionMsg_()
    : ACTION_TYPE()
    , MODE(0)
    , NAMES()
    , TYPES()
    , VALUES()  {
    }
  ActionMsg_(const ContainerAllocator& _alloc)
    : ACTION_TYPE(_alloc)
    , MODE(0)
    , NAMES(_alloc)
    , TYPES(_alloc)
    , VALUES(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ACTION_TYPE_type;
  _ACTION_TYPE_type ACTION_TYPE;

   typedef uint8_t _MODE_type;
  _MODE_type MODE;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _NAMES_type;
  _NAMES_type NAMES;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _TYPES_type;
  _TYPES_type TYPES;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _VALUES_type;
  _VALUES_type VALUES;





  typedef boost::shared_ptr< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ActionMsg_

typedef ::avl_bsd_translator::ActionMsg_<std::allocator<void> > ActionMsg;

typedef boost::shared_ptr< ::avl_bsd_translator::ActionMsg > ActionMsgPtr;
typedef boost::shared_ptr< ::avl_bsd_translator::ActionMsg const> ActionMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avl_bsd_translator::ActionMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avl_bsd_translator::ActionMsg_<ContainerAllocator1> & lhs, const ::avl_bsd_translator::ActionMsg_<ContainerAllocator2> & rhs)
{
  return lhs.ACTION_TYPE == rhs.ACTION_TYPE &&
    lhs.MODE == rhs.MODE &&
    lhs.NAMES == rhs.NAMES &&
    lhs.TYPES == rhs.TYPES &&
    lhs.VALUES == rhs.VALUES;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avl_bsd_translator::ActionMsg_<ContainerAllocator1> & lhs, const ::avl_bsd_translator::ActionMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avl_bsd_translator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26d51459ba77981700e1646ecfd1099d";
  }

  static const char* value(const ::avl_bsd_translator::ActionMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26d51459ba779817ULL;
  static const uint64_t static_value2 = 0x00e1646ecfd1099dULL;
};

template<class ContainerAllocator>
struct DataType< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avl_bsd_translator/ActionMsg";
  }

  static const char* value(const ::avl_bsd_translator::ActionMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#===============================================================================\n"
"# Autonomous Vehicle Library Backseat Driver\n"
"#\n"
"# Description: Defines a ROS message that contains an action\n"
"#===============================================================================\n"
"\n"
"string ACTION_TYPE\n"
"uint8 MODE\n"
"string[] NAMES\n"
"uint8[] TYPES\n"
"string[] VALUES\n"
;
  }

  static const char* value(const ::avl_bsd_translator::ActionMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ACTION_TYPE);
      stream.next(m.MODE);
      stream.next(m.NAMES);
      stream.next(m.TYPES);
      stream.next(m.VALUES);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avl_bsd_translator::ActionMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avl_bsd_translator::ActionMsg_<ContainerAllocator>& v)
  {
    s << indent << "ACTION_TYPE: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ACTION_TYPE);
    s << indent << "MODE: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.MODE);
    s << indent << "NAMES[]" << std::endl;
    for (size_t i = 0; i < v.NAMES.size(); ++i)
    {
      s << indent << "  NAMES[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.NAMES[i]);
    }
    s << indent << "TYPES[]" << std::endl;
    for (size_t i = 0; i < v.TYPES.size(); ++i)
    {
      s << indent << "  TYPES[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.TYPES[i]);
    }
    s << indent << "VALUES[]" << std::endl;
    for (size_t i = 0; i < v.VALUES.size(); ++i)
    {
      s << indent << "  VALUES[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.VALUES[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVL_BSD_TRANSLATOR_MESSAGE_ACTIONMSG_H
